#!/bin/sh
# Download a specific published distribution; no checkout, compiler or sudo.
set -eu
version=${1:-}
prefix=${2:-"$HOME/.local/share/pomar"}
case "$version" in v[0-9]*.[0-9]*.[0-9]*) ;; *) echo 'usage: sh install.sh vMAJOR.MINOR.PATCH[-prerelease] [absolute-prefix]' >&2; exit 2;; esac
# Refuse shell/path/URL metacharacters before using a tag in URLs or filenames.
case "$version" in *[!a-z0-9.-]* | *..*) echo 'invalid version' >&2; exit 2;; esac
[ "$(id -u)" != 0 ] || { echo 'Run as your own account, without sudo.' >&2; exit 2; }
[ "$(uname -s)" = Darwin ] && [ "$(uname -m)" = arm64 ] || { echo 'Pomar requires an Apple silicon Mac.' >&2; exit 2; }
major=$(sw_vers -productVersion | cut -d . -f 1)
[ "$major" -ge 26 ] || { echo 'Pomar requires macOS 26 or later.' >&2; exit 2; }
case "$prefix" in /*) ;; *) echo 'prefix must be absolute' >&2; exit 2;; esac
# TMPDIR respects the owner's storage convention; download space is temporary.
work=$(mktemp -d "${TMPDIR:-/tmp}/pomar-install.XXXXXXXX")
trap 'rm -rf "$work"' EXIT HUP INT TERM
asset="pomar-$version-darwin-arm64.tar.gz"
url="https://github.com/zeroemployeeorg/pomar/releases/download/$version"
curl --fail --silent --show-error --location --proto '=https' --proto-redir '=https' "$url/SHA256SUMS" -o "$work/SHA256SUMS"
curl --fail --silent --show-error --location --proto '=https' --proto-redir '=https' "$url/$asset" -o "$work/$asset"
# Only this exact archive line is used. Other assets do not affect installation.
awk -v name="$asset" '$2 == name && length($1) == 64 && $1 !~ /[^0-9a-f]/ { print; n++ } END { if (n != 1) exit 1 }' "$work/SHA256SUMS" > "$work/archive.sha256"
(cd "$work" && shasum -a 256 -c archive.sha256)
# This authenticated, checksummed archive is generated by pomar-dist with only
# regular files under one fixed root. Reject path escape before extraction.
root="pomar-$version-darwin-arm64"
tar -tzf "$work/$asset" > "$work/entries"
awk -v root="$root/" 'index($0,root)!=1 || $0 ~ /(^|\/)\.\.(\/|$)/ || $0 ~ /\/\// {bad=1} END {exit bad}' "$work/entries"
mkdir "$work/extracted"
tar -xzf "$work/$asset" -C "$work/extracted"
"$work/extracted/$root/bin/pomar" install -bundle "$work/extracted/$root" -prefix "$prefix"
printf '\nAdd this directory to PATH, then run pomar help:\n  %s/current/bin\n' "$prefix"
